# Generated by Django 5.1.6 on 2025-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('rate', models.IntegerField(verbose_name='امتیاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('pub_data', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('time', models.IntegerField(verbose_name='زمان لازم')),
                ('photo', models.ImageField(upload_to='foods/')),
            ],
        ),
    ]
