# Generated by Django 5.1.6 on 2025-02-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foods_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=10),
        ),
    ]
